import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1780319286109 implements MigrationInterface {
    name = 'Init1780319286109'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('super_admin', 'admin', 'fin_admin', 'ops_admin', 'parent')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "passwordHash" character varying, "role" "public"."users_role_enum" NOT NULL, "tenantId" uuid, "isActive" boolean NOT NULL DEFAULT true, "refreshTokenHash" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tenants_receipt_reset_policy_enum" AS ENUM('NEVER', 'YEARLY', 'ACADEMIC_YEAR', 'MONTHLY', 'DAILY')`);
        await queryRunner.query(`CREATE TYPE "public"."tenants_receipt_format_enum" AS ENUM('COMPACT_ACADEMIC', 'PREFIXED')`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" character varying, "tenantCode" character varying NOT NULL, "tenantName" character varying NOT NULL, "medium" character varying, "type" character varying, "school_code" character varying(32), "billing_mode" character varying(20), "monetization_enabled" boolean NOT NULL DEFAULT false, "boardType" character varying, "address" character varying, "city" character varying, "state" character varying, "country" character varying, "clientId" character varying NOT NULL, "secretKey" character varying NOT NULL, "receipt_prefix" character varying(20), "receipt_reset_policy" "public"."tenants_receipt_reset_policy_enum" NOT NULL DEFAULT 'ACADEMIC_YEAR', "receipt_start_number" integer NOT NULL DEFAULT '1', "receipt_format" "public"."tenants_receipt_format_enum" NOT NULL DEFAULT 'COMPACT_ACADEMIC', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3021c18db2b363ae9324c826c5a" UNIQUE ("code"), CONSTRAINT "UQ_f99e4a3fc1c4e456a05beb7b330" UNIQUE ("tenantCode"), CONSTRAINT "UQ_6bcf70aef358840cf45d738bc07" UNIQUE ("clientId"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_tenants_school_code" ON "tenants" ("school_code") `);
        await queryRunner.query(`CREATE TYPE "public"."tenant_configurations_environment_type_enum" AS ENUM('production', 'qa', 'development')`);
        await queryRunner.query(`CREATE TYPE "public"."tenant_configurations_gateway_type_enum" AS ENUM('razorpay', 'cashfree')`);
        await queryRunner.query(`CREATE TYPE "public"."tenant_configurations_payment_mode_enum" AS ENUM('test', 'production')`);
        await queryRunner.query(`CREATE TABLE "tenant_configurations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "environment_type" "public"."tenant_configurations_environment_type_enum" NOT NULL, "configuration_name" character varying(255) NOT NULL, "logo_url" text, "domain_url" text, "storage_access_key" text, "storage_connection_string" text, "storage_secret_key" text, "storage_bucket_name" character varying(255), "gateway_type" "public"."tenant_configurations_gateway_type_enum", "payment_client_id" text, "payment_secret_key" text, "payment_mode" "public"."tenant_configurations_payment_mode_enum" NOT NULL DEFAULT 'test', "payment_webhook_url" text, "smtp_host" character varying(255), "smtp_port" integer, "smtp_user" character varying(255), "smtp_password" text, "smtp_from_name" character varying(255), "smtp_from_email" character varying(255), "smtp_secure" boolean DEFAULT true, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_9e7ff5de5078546c335ce0c184a" UNIQUE ("tenant_id", "configuration_name"), CONSTRAINT "PK_5b97b6bdabfab3eb07552b3bbed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_25b963685872986565fcd79333" ON "tenant_configurations" ("tenant_id", "environment_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_2c4df2e9d0e3988278fad6ae53" ON "tenant_configurations" ("tenant_id", "is_active") `);
        await queryRunner.query(`CREATE TABLE "templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying, "adminId" character varying, "name" character varying NOT NULL, "message" text NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "category" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_515948649ce0bbbe391de702ae5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "system_metadata" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying(50) NOT NULL, "value" character varying(100) NOT NULL, "label" character varying(150), "description" text, "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_system_metadata_type_value" UNIQUE ("type", "value"), CONSTRAINT "PK_fc0dd183baf67b24074f157469a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_system_metadata_type_active" ON "system_metadata" ("type", "is_active") `);
        await queryRunner.query(`CREATE TABLE "students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "school_code" character varying(100) NOT NULL, "admission_number" character varying(50) NOT NULL, "academic_year" character varying(20) NOT NULL, "name" character varying(150) NOT NULL, "email" character varying(150) NOT NULL, "phone_number" character varying(20) NOT NULL, "class" character varying(20) NOT NULL, "section" character varying(10) NOT NULL, "roll_no" character varying(20) NOT NULL, "img_url" text, "pickup_location" character varying(200), "drop_location" character varying(200), "father_name" character varying(150), "mother_name" character varying(150), "date_of_admission" date, "identity_id" uuid, "tc_issued_at" TIMESTAMP WITH TIME ZONE, "tc_reason" character varying(500), "tc_certificate_no" character varying(50), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_students_tenant_branch_admission_year" UNIQUE ("tenant_id", "school_code", "admission_number", "academic_year"), CONSTRAINT "PK_7d7f07271ad4ce999880713f05e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_students_identity" ON "students" ("identity_id") `);
        await queryRunner.query(`CREATE INDEX "idx_students_tenant_branch_year" ON "students" ("tenant_id", "school_code", "academic_year") `);
        await queryRunner.query(`CREATE TABLE "student_identities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "display_name" character varying(150) NOT NULL, "date_of_birth" date, "gender" character varying(20), "primary_phone" character varying(20), "primary_email" character varying(150), "photo_url" text, "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_59d54d7ebc39d4ad3e703b31e51" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_student_identities_tenant_name" ON "student_identities" ("tenant_id", "display_name") `);
        await queryRunner.query(`CREATE INDEX "idx_student_identities_tenant_email" ON "student_identities" ("tenant_id", "primary_email") `);
        await queryRunner.query(`CREATE INDEX "idx_student_identities_tenant_phone" ON "student_identities" ("tenant_id", "primary_phone") `);
        await queryRunner.query(`CREATE TABLE "social_reactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "post_id" uuid NOT NULL, "author_kind" character varying(20) NOT NULL, "author_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_social_reactions_post_user" UNIQUE ("post_id", "author_kind", "author_id"), CONSTRAINT "PK_8bedf62c381ac3f8f039730449c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_social_reactions_post" ON "social_reactions" ("post_id") `);
        await queryRunner.query(`CREATE TYPE "public"."social_posts_kind_enum" AS ENUM('POST', 'EVENT', 'ANNOUNCEMENT')`);
        await queryRunner.query(`CREATE TABLE "social_posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "author_admin_id" uuid, "author_name" character varying(150), "kind" "public"."social_posts_kind_enum" NOT NULL DEFAULT 'POST', "title" character varying(200) NOT NULL, "excerpt" character varying(280), "body" text NOT NULL DEFAULT '', "event_at" TIMESTAMP WITH TIME ZONE, "location" character varying(200), "tags" character varying(300), "is_public" boolean NOT NULL DEFAULT true, "is_published" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2161864ea79f14525b8804bd7ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_social_posts_public_published" ON "social_posts" ("is_public", "is_published", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_social_posts_tenant_published" ON "social_posts" ("tenant_id", "is_published", "created_at") `);
        await queryRunner.query(`CREATE TABLE "social_post_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "post_id" uuid NOT NULL, "url" text NOT NULL, "alt" character varying(200), "order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9ff2e21cc2df31abb125c58e991" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_social_post_images_post_order" ON "social_post_images" ("post_id", "order") `);
        await queryRunner.query(`CREATE TABLE "social_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "post_id" uuid NOT NULL, "author_kind" character varying(20) NOT NULL, "author_id" uuid NOT NULL, "author_name" character varying(150), "body" character varying(1000) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5969df03850043d5d63567eccbe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_social_comments_post_created" ON "social_comments" ("post_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."receipt_templates_kind_enum" AS ENUM('ONLINE', 'OFFLINE', 'BOTH')`);
        await queryRunner.query(`CREATE TABLE "receipt_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "kind" "public"."receipt_templates_kind_enum" NOT NULL DEFAULT 'BOTH', "header_html" text NOT NULL DEFAULT '', "body_html" text NOT NULL DEFAULT '', "footer_html" text NOT NULL DEFAULT '', "is_default" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_receipt_templates_tenant_name" UNIQUE ("tenant_id", "name"), CONSTRAINT "PK_291a63c22ca0bbdabc17ec34cdd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_receipt_templates_tenant_active" ON "receipt_templates" ("tenant_id", "is_active") `);
        await queryRunner.query(`CREATE TABLE "penalties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_c917b09222ad10103d984fc4e7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."fees_payment_status_enum" AS ENUM('UNPAID', 'PARTIAL', 'PAID')`);
        await queryRunner.query(`CREATE TABLE "fees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "branch" character varying(100) NOT NULL, "academic_year" character varying(20) NOT NULL, "student_id" uuid NOT NULL, "term" character varying(30) NOT NULL, "original_amount" numeric(12,2) NOT NULL, "total_penalty" numeric(12,2) NOT NULL DEFAULT '0', "total_discount" numeric(12,2) NOT NULL DEFAULT '0', "net_amount" numeric(12,2) NOT NULL, "paid_amount" numeric(12,2) NOT NULL DEFAULT '0', "payment_status" "public"."fees_payment_status_enum" NOT NULL DEFAULT 'UNPAID', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_fees_tenant_branch_student_year_term" UNIQUE ("tenant_id", "branch", "student_id", "academic_year", "term"), CONSTRAINT "chk_fees_paid_amount_non_negative" CHECK ("paid_amount" >= 0), CONSTRAINT "chk_fees_discount_non_negative" CHECK ("total_discount" >= 0), CONSTRAINT "chk_fees_penalty_non_negative" CHECK ("total_penalty" >= 0), CONSTRAINT "chk_fees_original_amount_non_negative" CHECK ("original_amount" >= 0), CONSTRAINT "PK_97f3a1b1b8ee5674fd4da93f461" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_fees_tenant_status" ON "fees" ("tenant_id", "payment_status") `);
        await queryRunner.query(`CREATE INDEX "idx_fees_tenant_branch_year" ON "fees" ("tenant_id", "branch", "academic_year") `);
        await queryRunner.query(`CREATE TYPE "public"."penalty_rules_term_enum" AS ENUM('1st Term Fee', '2nd Term Fee', '3rd Term Fee', '4th Term Fee', '5th Term Fee')`);
        await queryRunner.query(`CREATE TYPE "public"."penalty_rules_amount_type_enum" AS ENUM('FLAT', 'PER_DAY')`);
        await queryRunner.query(`CREATE TABLE "penalty_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "branch" character varying(100), "academic_year" character varying(20), "term" "public"."penalty_rules_term_enum", "trigger_after_days" integer NOT NULL DEFAULT '0', "amount_type" "public"."penalty_rules_amount_type_enum" NOT NULL DEFAULT 'FLAT', "amount" numeric(12,2) NOT NULL, "max_amount" numeric(12,2), "is_active" boolean NOT NULL DEFAULT true, "description" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f17c98d146939f4d584862a302f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_pr_tenant_active" ON "penalty_rules" ("tenant_id", "is_active") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_payment_type_enum" AS ENUM('online', 'offline')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_gateway_enum" AS ENUM('razorpay', 'cashfree')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('created', 'paid', 'failed', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "fee_id" uuid, "payment_type" "public"."payments_payment_type_enum" NOT NULL DEFAULT 'online', "gateway" "public"."payments_gateway_enum", "status" "public"."payments_status_enum" NOT NULL DEFAULT 'created', "gatewayOrderId" character varying, "gatewayPaymentId" character varying, "cheque_number" character varying(50), "cheque_date" date, "dd_date" date, "amount" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'INR', "notes" character varying, "paidAt" TIMESTAMP WITH TIME ZONE, "failureReason" text, "refundedAmount" integer, "refundedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cd19dcf01dffc25c7a84acbb40c" UNIQUE ("gatewayOrderId"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b6e82c979b19f8df6fc4d1a2fd" ON "payments" ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_63a284e4446aa8efee9dff1ea8" ON "payments" ("tenantId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."transactions_type_enum" AS ENUM('order_created', 'payment_success', 'payment_failed')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_gateway_enum" AS ENUM('razorpay', 'cashfree')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_status_enum" AS ENUM('created', 'paid', 'failed', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "paymentId" uuid NOT NULL, "type" "public"."transactions_type_enum" NOT NULL, "gateway" "public"."transactions_gateway_enum" NOT NULL, "status" "public"."transactions_status_enum" NOT NULL, "gatewayOrderId" character varying NOT NULL, "gatewayPaymentId" character varying, "amount" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'INR', "notes" character varying, "paymentDetails" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_audit_logs_action_enum" AS ENUM('ORDER_CREATED', 'PAYMENT_VERIFIED', 'PAYMENT_VERIFY_FAILED', 'WEBHOOK_RECEIVED', 'WEBHOOK_SIGNATURE_FAILED', 'WEBHOOK_GATEWAY_UNKNOWN', 'WEBHOOK_DUPLICATE', 'WEBHOOK_ORDER_NOT_FOUND', 'PAYMENT_STATUS_CHANGED')`);
        await queryRunner.query(`CREATE TABLE "payment_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "paymentId" character varying, "transactionId" character varying, "action" "public"."payment_audit_logs_action_enum" NOT NULL, "gateway" character varying, "gatewayOrderId" character varying, "gatewayPaymentId" character varying, "eventType" character varying, "fromStatus" character varying, "toStatus" character varying, "actor" character varying, "ipAddress" character varying, "isError" boolean NOT NULL DEFAULT false, "errorMessage" text, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1f3c2d028e1ec2c6e889bf3e4b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0859dd71caf91cd1a3793f3dde" ON "payment_audit_logs" ("paymentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2cac550684230a3572af1b75fe" ON "payment_audit_logs" ("gatewayOrderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e39ae14dda18dc8e13686c33a" ON "payment_audit_logs" ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."parent_students_relationship_enum" AS ENUM('father', 'mother', 'guardian')`);
        await queryRunner.query(`CREATE TABLE "parent_students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "parent_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "branch" character varying(100) NOT NULL, "admission_number" character varying(50) NOT NULL, "relationship" "public"."parent_students_relationship_enum" NOT NULL DEFAULT 'guardian', "is_primary" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "uq_parent_students_link" UNIQUE ("parent_id", "tenant_id", "branch", "admission_number"), CONSTRAINT "PK_2707b9be03fad93515167debe7a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_parent_students_lookup" ON "parent_students" ("tenant_id", "branch", "admission_number") `);
        await queryRunner.query(`CREATE TABLE "parents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying(150) NOT NULL, "email" character varying(150) NOT NULL, "phone_number" character varying(20), "is_active" boolean NOT NULL DEFAULT true, "refresh_token_hash" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_parents_tenant_email" UNIQUE ("tenant_id", "email"), CONSTRAINT "PK_9a4dc67c7b8e6a9cb918938d353" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_parents_tenant" ON "parents" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "parent_otps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "email" character varying(150) NOT NULL, "otp_hash" character varying NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "is_used" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a3cc1e00b84f6ee6a231293afb1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_parent_otps_tenant_email" ON "parent_otps" ("tenant_id", "email") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "recipient_id" uuid, "recipient_role" character varying(50), "title" character varying(200) NOT NULL, "body" text, "type" character varying(50) NOT NULL DEFAULT 'general', "link_url" character varying(500), "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_notif_tenant_recipient" ON "notifications" ("tenant_id", "recipient_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "branch" character varying(100), "url" text NOT NULL, "storage_key" text NOT NULL, "file_name" character varying(255), "mime_type" character varying(100) NOT NULL, "size_bytes" integer NOT NULL DEFAULT '0', "caption" character varying(300), "uploaded_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_f4e0fcac36e050de337b670d8bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_media_tenant_created" ON "media" ("tenant_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "receipt_sequences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "period_key" character varying(30) NOT NULL, "current_value" integer NOT NULL DEFAULT '0', "last_issued_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_receipt_sequences_tenant_period" UNIQUE ("tenant_id", "period_key"), CONSTRAINT "PK_cced0c6b4479721f75c051ff175" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."fee_payments_payment_type_enum" AS ENUM('RAZORPAY', 'CASHFREE', 'UPI', 'NETBANKING', 'CARD', 'CASH', 'CHEQUE', 'DD', 'POS', 'NEFT')`);
        await queryRunner.query(`CREATE TYPE "public"."fee_payments_clearance_status_enum" AS ENUM('PENDING', 'CLEARED', 'BOUNCED', 'NA')`);
        await queryRunner.query(`CREATE TABLE "fee_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "branch" character varying(100) NOT NULL, "fee_id" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "payment_type" "public"."fee_payments_payment_type_enum" NOT NULL, "receipt_number" character varying(50), "order_id" character varying(100), "transaction_id" character varying(100), "cheque_number" character varying(50), "cheque_date" date, "dd_number" character varying(50), "dd_date" date, "bank_name" character varying(100), "bank_branch" character varying(100), "drawer_name" character varying(150), "card_last4" character varying(4), "clearance_status" "public"."fee_payments_clearance_status_enum" NOT NULL DEFAULT 'NA', "notes" text, "paid_at" TIMESTAMP WITH TIME ZONE NOT NULL, "recorded_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_fp_receipt_number" UNIQUE ("receipt_number"), CONSTRAINT "chk_fp_amount_positive" CHECK ("amount" > 0), CONSTRAINT "PK_9bd9fdfc57a96cadaefe822956d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_fp_clearance_pending" ON "fee_payments" ("tenant_id", "clearance_status") `);
        await queryRunner.query(`CREATE INDEX "idx_fp_tenant_paid_at" ON "fee_payments" ("tenant_id", "paid_at") `);
        await queryRunner.query(`CREATE INDEX "idx_fp_fee" ON "fee_payments" ("fee_id") `);
        await queryRunner.query(`CREATE TYPE "public"."fee_adjustments_kind_enum" AS ENUM('PENALTY_ADD', 'PENALTY_WAIVE', 'DISCOUNT_ADD', 'DISCOUNT_WAIVE')`);
        await queryRunner.query(`CREATE TABLE "fee_adjustments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "fee_id" uuid NOT NULL, "kind" "public"."fee_adjustments_kind_enum" NOT NULL, "amount" numeric(12,2) NOT NULL, "reason" text, "created_by_id" uuid, "created_by_email" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f4c14e63162538e2d12c9694cfb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_fee_adjustments_tenant_created" ON "fee_adjustments" ("tenant_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_fee_adjustments_fee_created" ON "fee_adjustments" ("fee_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_message_preview" character varying(200), "last_message_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_conversations_last_msg" ON "conversations" ("last_message_at") `);
        await queryRunner.query(`CREATE TABLE "conversation_participants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "admin_id" uuid NOT NULL, "tenant_id" uuid, "last_read_message_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_conv_participants_conv_admin" UNIQUE ("conversation_id", "admin_id"), CONSTRAINT "PK_61b51428ad9453f5921369fbe94" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_conv_participants_admin" ON "conversation_participants" ("admin_id") `);
        await queryRunner.query(`CREATE TABLE "chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "sender_id" uuid NOT NULL, "body" text NOT NULL DEFAULT '', "reply_to_id" uuid, "attachment_url" text, "attachment_name" character varying(255), "attachment_mime" character varying(150), "attachment_size" integer, "attachments" jsonb, "reactions" jsonb, "edited_at" TIMESTAMP WITH TIME ZONE, "deleted_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_40c55ee0e571e268b0d3cd37d10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_chat_messages_conv_created" ON "chat_messages" ("conversation_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "actorId" character varying, "actorEmail" character varying, "actorRole" character varying, "method" character varying NOT NULL, "path" character varying NOT NULL, "statusCode" integer, "isError" boolean NOT NULL DEFAULT false, "durationMs" integer, "ipAddress" character varying, "payload" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_01079ff63347605d96a71b85fc" ON "audit_logs" ("method", "path") `);
        await queryRunner.query(`CREATE INDEX "IDX_2dc33f7f3c22e2e7badafca1d1" ON "audit_logs" ("actorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f09b40d69c2488932373effd4e" ON "audit_logs" ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."adjustment_approvals_action_enum" AS ENUM('DISCOUNT_ADD_BULK', 'DISCOUNT_WAIVE_BULK', 'PENALTY_WAIVE_BULK', 'DISCOUNT_ADD_SINGLE', 'DISCOUNT_WAIVE_SINGLE', 'PENALTY_WAIVE_SINGLE')`);
        await queryRunner.query(`CREATE TYPE "public"."adjustment_approvals_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "adjustment_approvals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "branch" character varying(100), "action" "public"."adjustment_approvals_action_enum" NOT NULL, "status" "public"."adjustment_approvals_status_enum" NOT NULL DEFAULT 'PENDING', "summary" text NOT NULL, "payload" jsonb NOT NULL, "requested_by_id" uuid NOT NULL, "requested_by_email" character varying, "requested_by_role" character varying(50) NOT NULL, "decided_by_id" uuid, "decided_at" TIMESTAMP WITH TIME ZONE, "decision_note" text, "result" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3234d90c73eee1a56e063475f97" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_approvals_tenant_status" ON "adjustment_approvals" ("tenant_id", "status", "created_at") `);
        await queryRunner.query(`CREATE TABLE "announcements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "title" character varying(200) NOT NULL, "body" text, "event_date" TIMESTAMP WITH TIME ZONE, "audience_role" character varying(50), "published_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_b3ad760876ff2e19d58e05dc8b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_announcements_tenant_published" ON "announcements" ("tenant_id", "published_at") `);
        await queryRunner.query(`CREATE TABLE "admins" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "email" character varying NOT NULL, "role" character varying(50) NOT NULL, "branch" character varying, "clientId" character varying NOT NULL, "secretKey" character varying NOT NULL, "passwordHash" character varying NOT NULL, "tenantId" character varying, "isActive" boolean NOT NULL DEFAULT true, "refreshTokenHash" character varying, "passwordResetTokenHash" character varying, "passwordResetExpiresAt" TIMESTAMP, "emailVerified" boolean NOT NULL DEFAULT false, "emailVerificationTokenHash" character varying, "emailVerificationExpiresAt" TIMESTAMP, "failedLoginAttempts" integer NOT NULL DEFAULT '0', "lockedUntil" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_883a0056417cd1a3c207c49d97a" UNIQUE ("clientId"), CONSTRAINT "uq_admin_email_tenant" UNIQUE ("email", "tenantId"), CONSTRAINT "PK_e3b38270c97a854c48d2e80874e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_admin_email" ON "admins" ("email") `);
        await queryRunner.query(`CREATE TABLE "academic_years" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "academic_year" character varying(20) NOT NULL, "is_current_year" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT false, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_academic_years_tenant_year" UNIQUE ("tenant_id", "academic_year"), CONSTRAINT "PK_2021b90bfbfa6c9da7df34ca1cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a68993c73df4864100a7d63333" ON "academic_years" ("tenant_id") `);
        await queryRunner.query(`ALTER TABLE "fees" ADD CONSTRAINT "FK_1ad84dd647a6c4464ed46829b25" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_02a66e9bd67a2d3bd8e051afa69" FOREIGN KEY ("fee_id") REFERENCES "fees"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_721af04ac41f7598ecb59f5e66f" FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent_students" ADD CONSTRAINT "FK_0b5ad7b1365e1d5e0181e86cbc5" FOREIGN KEY ("parent_id") REFERENCES "parents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fee_payments" ADD CONSTRAINT "FK_a6180a0dd34aa943649ac1df7eb" FOREIGN KEY ("fee_id") REFERENCES "fees"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "fee_payments" DROP CONSTRAINT "FK_a6180a0dd34aa943649ac1df7eb"`);
        await queryRunner.query(`ALTER TABLE "parent_students" DROP CONSTRAINT "FK_0b5ad7b1365e1d5e0181e86cbc5"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_721af04ac41f7598ecb59f5e66f"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_02a66e9bd67a2d3bd8e051afa69"`);
        await queryRunner.query(`ALTER TABLE "fees" DROP CONSTRAINT "FK_1ad84dd647a6c4464ed46829b25"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a68993c73df4864100a7d63333"`);
        await queryRunner.query(`DROP TABLE "academic_years"`);
        await queryRunner.query(`DROP INDEX "public"."idx_admin_email"`);
        await queryRunner.query(`DROP TABLE "admins"`);
        await queryRunner.query(`DROP INDEX "public"."idx_announcements_tenant_published"`);
        await queryRunner.query(`DROP TABLE "announcements"`);
        await queryRunner.query(`DROP INDEX "public"."idx_approvals_tenant_status"`);
        await queryRunner.query(`DROP TABLE "adjustment_approvals"`);
        await queryRunner.query(`DROP TYPE "public"."adjustment_approvals_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."adjustment_approvals_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f09b40d69c2488932373effd4e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2dc33f7f3c22e2e7badafca1d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01079ff63347605d96a71b85fc"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_chat_messages_conv_created"`);
        await queryRunner.query(`DROP TABLE "chat_messages"`);
        await queryRunner.query(`DROP INDEX "public"."idx_conv_participants_admin"`);
        await queryRunner.query(`DROP TABLE "conversation_participants"`);
        await queryRunner.query(`DROP INDEX "public"."idx_conversations_last_msg"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fee_adjustments_fee_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fee_adjustments_tenant_created"`);
        await queryRunner.query(`DROP TABLE "fee_adjustments"`);
        await queryRunner.query(`DROP TYPE "public"."fee_adjustments_kind_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fp_fee"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fp_tenant_paid_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fp_clearance_pending"`);
        await queryRunner.query(`DROP TABLE "fee_payments"`);
        await queryRunner.query(`DROP TYPE "public"."fee_payments_clearance_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."fee_payments_payment_type_enum"`);
        await queryRunner.query(`DROP TABLE "receipt_sequences"`);
        await queryRunner.query(`DROP INDEX "public"."idx_media_tenant_created"`);
        await queryRunner.query(`DROP TABLE "media"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notif_tenant_recipient"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."idx_parent_otps_tenant_email"`);
        await queryRunner.query(`DROP TABLE "parent_otps"`);
        await queryRunner.query(`DROP INDEX "public"."idx_parents_tenant"`);
        await queryRunner.query(`DROP TABLE "parents"`);
        await queryRunner.query(`DROP INDEX "public"."idx_parent_students_lookup"`);
        await queryRunner.query(`DROP TABLE "parent_students"`);
        await queryRunner.query(`DROP TYPE "public"."parent_students_relationship_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e39ae14dda18dc8e13686c33a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cac550684230a3572af1b75fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0859dd71caf91cd1a3793f3dde"`);
        await queryRunner.query(`DROP TABLE "payment_audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."payment_audit_logs_action_enum"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_gateway_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63a284e4446aa8efee9dff1ea8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6e82c979b19f8df6fc4d1a2fd"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_gateway_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_payment_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pr_tenant_active"`);
        await queryRunner.query(`DROP TABLE "penalty_rules"`);
        await queryRunner.query(`DROP TYPE "public"."penalty_rules_amount_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."penalty_rules_term_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fees_tenant_branch_year"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fees_tenant_status"`);
        await queryRunner.query(`DROP TABLE "fees"`);
        await queryRunner.query(`DROP TYPE "public"."fees_payment_status_enum"`);
        await queryRunner.query(`DROP TABLE "penalties"`);
        await queryRunner.query(`DROP INDEX "public"."idx_receipt_templates_tenant_active"`);
        await queryRunner.query(`DROP TABLE "receipt_templates"`);
        await queryRunner.query(`DROP TYPE "public"."receipt_templates_kind_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_social_comments_post_created"`);
        await queryRunner.query(`DROP TABLE "social_comments"`);
        await queryRunner.query(`DROP INDEX "public"."idx_social_post_images_post_order"`);
        await queryRunner.query(`DROP TABLE "social_post_images"`);
        await queryRunner.query(`DROP INDEX "public"."idx_social_posts_tenant_published"`);
        await queryRunner.query(`DROP INDEX "public"."idx_social_posts_public_published"`);
        await queryRunner.query(`DROP TABLE "social_posts"`);
        await queryRunner.query(`DROP TYPE "public"."social_posts_kind_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_social_reactions_post"`);
        await queryRunner.query(`DROP TABLE "social_reactions"`);
        await queryRunner.query(`DROP INDEX "public"."idx_student_identities_tenant_phone"`);
        await queryRunner.query(`DROP INDEX "public"."idx_student_identities_tenant_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_student_identities_tenant_name"`);
        await queryRunner.query(`DROP TABLE "student_identities"`);
        await queryRunner.query(`DROP INDEX "public"."idx_students_tenant_branch_year"`);
        await queryRunner.query(`DROP INDEX "public"."idx_students_identity"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP INDEX "public"."idx_system_metadata_type_active"`);
        await queryRunner.query(`DROP TABLE "system_metadata"`);
        await queryRunner.query(`DROP TABLE "templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c4df2e9d0e3988278fad6ae53"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25b963685872986565fcd79333"`);
        await queryRunner.query(`DROP TABLE "tenant_configurations"`);
        await queryRunner.query(`DROP TYPE "public"."tenant_configurations_payment_mode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tenant_configurations_gateway_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tenant_configurations_environment_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tenants_school_code"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_receipt_format_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_receipt_reset_policy_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
